name: SMS Spam Detection CI

on:
  # Trigger workflow on push or pull request to main or master branches
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit pandas numpy scikit-learn matplotlib seaborn requests

      # Run the spam detection app (as part of test)
      - name: Run streamlit app
        run: |
          streamlit run main.py --server.headless true

      # Linting using flake8
      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      # Run unit tests
      - name: Run tests
        run: |
          pip install pytest
          pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Streamlit
        env:
          STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}
        run: |
          # Assuming deployment is handled via Streamlit sharing
          streamlit deploy main.py --api-key $STREAMLIT_API_KEY
